FROM node:latest AS build

RUN useradd -ms /bin/sh -u 1001 app
USER app

WORKDIR /app
COPY package*.json .
RUN npm ci

COPY --chown=app:app . /app

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]
